config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'quotes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
require 'rubygems'
require 'json'

class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    text = quote_params[:text]

    if text == 'help' or text == ''
      json = { text: "Utilize o comando `/novaquotes` para salvar frases ou citações hilárias que aconteceram na Novatics.\nAlguns exemplos:\n•`/novaquotes` Só sei que nada sei.\n•`/novaquotes` Com grandes poderes vem grandes responsabilidades.\n\nPara abrir este menu de ajuda, use `/novaquotes help`.\nPara ver todas as frases salvas: http://novaquote.herokuapp.com" }
      respond_to { |format| format.json { render json: json, status: :ok, location: @quote } }
      return
    end

    begin
      user = get_user_profile(quote_params)
    rescue Exception => e
      json = { text: "Ocorreu um erro: #{e.message}" }
      respond_to { |format| format.json { render json: json, status: :ok, location: @quote } }
      return
    end

    phrase = text.capitalize
    @quote = Quote.new(author: user['real_name'], message: phrase, image: user['image_32'])

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Frase adicionada com sucesso.' }

        json = {
          text: "Frase adicionada: #{phrase}.",
          attachments: [{
            title: "Ver todas as frases",
            title_link: "http://novaquote.herokuapp.com",
          }]
        }
        format.json { render json: json, status: :ok, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Frase atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Frase apagada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.permit!
    end

    def get_user_profile(params)
      client = HTTPClient.new
      token = 'xoxp-72060886741-72051010868-73339716976-8d6ea2a87f'
      user = params[:user_id]
      url = "https://slack.com/api/users.profile.get?token=#{token}&user=#{user}"
      str = client.get_content(url)
      response = JSON.parse(str)
      raise response['error'] if not response['ok']
      profile = response['profile']
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlackBot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css" rel="stylesheet"/>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(quote) do |f| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label 'Frase' %>
    <%= f.text_field :message, placeholder: '"Só sei que nada sei"' %>
  </div>

  <div class="field form-group">
    <%= f.label 'Autor' %>
    <%= f.text_field :author, placeholder: 'Platão' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Ver', @quote %> |
<%= link_to 'Voltar', quotes_path %>

app/views/quotes/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<%= nav_bar brand: "Frases hilárias ditas na Novatics", brand_link: "/" %>

<table class="table table-bordered table-hover table-responsive">
  <tbody>
    <div class="card-columns">
      <% @quotes.each do |quote| %>
        <div class="card card-inverse text-xs-center">
          <div class="card-block">
            <%= image_tag(quote.image, size: "32x32", class: "img-circle", style: "float: left") %>
            <blockquote class="card-blockquote">
              <p><%= quote.message %></p>
              <footer><cite title="Source Title"><%= quote.author %></cite></footer>
            </blockquote>
          </div>
        </div>
      <% end %>
    </div>
  </tbody>
</table>

<br>

<%= link_to 'Nova frase', new_quote_path %>
</div>

<script>
  var cards = document.getElementsByClassName('card');
  for (i = 0; i < cards.length; i++) {
      var randomColor = '#' + Math.floor(Math.random() * 16777215).toString(16);
      cards[i].style.backgroundColor = randomColor;
      cards[i].style.borderColor = randomColor;
  }
</script>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Voltar', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @quote.message %>
</p>

<p>
  <strong>Author:</strong>
  <%= @quote.author %>
</p>

<%= link_to 'Editar', edit_quote_path(@quote) %> |
<%= link_to 'Voltar', quotes_path %>